// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  if (
    (await import('process')).platform === 'darwin' ||
    (await import('process')).platform === 'linux'
  ) {
    await import('./swift.js')
  }

  test.resume()
}
