// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  await import('./swift.js')
  await import('./cross-language.js')

  test.resume()
}
