// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  if (process.platform === 'darwin' || process.platform === 'linux') {
    console.log('running swift tests')
    await import('./swift.js')
  }

  test.resume()
}
