module.exports = function generateSwift(hyperschema) {
  const lines = [
    '// This file is autogenerated by the hyperschema compiler',
    '// !!DO NOT EDIT THIS FILE!!',
    `// Schema Version: ${hyperschema.version}`,
    '',
    'import CompactEncoding',
    'import Foundation',
    '',
    'func encode<C: Codec>(_ codec: C, _ value: C.Value) -> Data {',
    '  var state = State()',
    '  codec.preencode(&state, value)',
    '  state.allocate()',
    '  try! codec.encode(&state, value)',
    '  return state.buffer',
    '}',
    '',
    'func decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {',
    '  var state = State(data)',
    '  return try codec.decode(&state)',
    '}'
  ]

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (!type.isStruct) continue
    lines.push('', ...generateStruct(type))
  }

  return lines.join('\n') + '\n'
}

function toSwiftTypeName(name) {
  return name
    .split('-')
    .map((s) => (s.length ? s[0].toUpperCase() + s.slice(1) : s))
    .join('')
}

function toSwiftInstanceName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

function resolveBaseType(type) {
  if (type.isAlias) return resolveBaseType(type.type)
  return type
}

function getSwiftType(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return 'UInt'
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecVar(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return '_uint'
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecInit(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return 'Primitive.UInt()'
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function generateStruct(struct) {
  const typeName = toSwiftTypeName(struct.name)
  const instanceName = toSwiftInstanceName(struct.name)
  const fields = struct.fields

  // Collect unique codecs needed by this struct
  const codecs = new Map()
  for (const field of fields) {
    const varName = getSwiftCodecVar(field.type)
    if (!codecs.has(varName)) codecs.set(varName, getSwiftCodecInit(field.type))
  }

  const lines = []

  lines.push(`// ${struct.fqn}`)
  lines.push(`public struct ${typeName} {`)
  for (const field of fields) {
    lines.push(`  public var ${field.name}: ${getSwiftType(field.type)}`)
  }
  lines.push('}')
  lines.push('')

  lines.push(`public struct ${typeName}Codec: Codec {`)
  lines.push(`  public typealias Value = ${typeName}`)
  lines.push('')
  for (const [varName, init] of codecs) {
    lines.push(`  public let ${varName} = ${init}`)
  }
  lines.push('')

  lines.push(`  public func preencode(_ state: inout State, _ value: ${typeName}) {`)
  for (const field of fields) {
    lines.push(`    ${getSwiftCodecVar(field.type)}.preencode(&state, value.${field.name})`)
  }
  lines.push('  }')
  lines.push('')

  lines.push(`  public func encode(_ state: inout State, _ value: ${typeName}) throws {`)
  for (const field of fields) {
    lines.push(`    try ${getSwiftCodecVar(field.type)}.encode(&state, value.${field.name})`)
  }
  lines.push('  }')
  lines.push('')

  lines.push(`  public func decode(_ state: inout State) throws -> ${typeName} {`)
  lines.push(`    return ${typeName}(`)
  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const comma = i < fields.length - 1 ? ',' : ''
    lines.push(`      ${field.name}: try ${getSwiftCodecVar(field.type)}.decode(&state)${comma}`)
  }
  lines.push('    )')
  lines.push('  }')
  lines.push('}')
  lines.push('')

  lines.push(`public let ${instanceName} = ${typeName}Codec()`)

  return lines
}
