module.exports = function generateSwift(hyperschema) {
  hyperschema.linkAll()
  let str = ''
  str += '// This file is autogenerated by the hyperschema compiler\n'
  str += `// Schema Version: ${hyperschema.version}\n`
  str += '\n'
  str += 'import CompactEncoding\n'
  str += 'import Foundation\n'
  str += '\n'
  str += 'func encode<C: Codec>(_ codec: C, _ value: C.Value) -> Data {\n'
  str += '  var state = State()\n'
  str += '  codec.preencode(&state, value)\n'
  str += '  state.allocate()\n'
  str += '  try! codec.encode(&state, value)\n'
  str += '  return state.buffer\n'
  str += '}\n'
  str += '\n'
  str += 'func decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {\n'
  str += '  var state = State(data)\n'
  str += '  return try codec.decode(&state)\n'
  str += '}\n'

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (!type.isStruct) continue
    str += '\n'
    str += generateStruct(type)
  }

  return str
}

function toSwiftTypeName(name) {
  return name
    .split('-')
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('')
}

function toSwiftInstanceName(name) {
  const pascal = toSwiftTypeName(name)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

function resolveBaseType(type) {
  if (type.isAlias) return resolveBaseType(type.type)
  return type
}

function getSwiftType(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return 'UInt'
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecVar(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return '_uint'
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function getSwiftCodecInit(type) {
  const base = resolveBaseType(type)
  if (base.name === 'uint') return 'Primitive.UInt()'
  throw new Error(`Unsupported type for Swift codegen: ${base.name}`)
}

function generateStruct(struct) {
  const typeName = toSwiftTypeName(struct.name)
  const instanceName = toSwiftInstanceName(struct.name)
  const fields = struct.fields

  // Collect unique codecs needed by this struct
  const codecs = new Map()
  for (const field of fields) {
    const varName = getSwiftCodecVar(field.type)
    if (!codecs.has(varName)) codecs.set(varName, getSwiftCodecInit(field.type))
  }

  let str = ''

  str += `// ${struct.fqn}\n`
  str += `struct ${typeName} {\n`
  for (const field of fields) {
    str += `  var ${field.name}: ${getSwiftType(field.type)}\n`
  }
  str += '}\n'
  str += '\n'

  str += `struct ${typeName}Codec: Codec {\n`
  str += `  typealias Value = ${typeName}\n`
  str += '\n'
  for (const [varName, init] of codecs) {
    str += `  let ${varName} = ${init}\n`
  }
  str += '\n'

  str += `  func preencode(_ state: inout State, _ value: ${typeName}) {\n`
  for (const field of fields) {
    str += `    ${getSwiftCodecVar(field.type)}.preencode(&state, value.${field.name})\n`
  }
  str += '  }\n'
  str += '\n'

  str += `  func encode(_ state: inout State, _ value: ${typeName}) throws {\n`
  for (const field of fields) {
    str += `    try ${getSwiftCodecVar(field.type)}.encode(&state, value.${field.name})\n`
  }
  str += '  }\n'
  str += '\n'

  str += `  func decode(_ state: inout State) throws -> ${typeName} {\n`
  str += `    return ${typeName}(\n`
  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const comma = i < fields.length - 1 ? ',' : ''
    str += `      ${field.name}: try ${getSwiftCodecVar(field.type)}.decode(&state)${comma}\n`
  }
  str += '    )\n'
  str += '  }\n'
  str += '}\n'
  str += '\n'

  str += `let ${instanceName} = ${typeName}Codec()\n`

  return str
}
