// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @namespace-1/parent2
const encoding0 = {
  preencode(state, m) {
    let flags = (m.info ? 1 : 0) | (m.parent ? 2 : 0)
    if (m.parent) {
      flags |=
        ((m.parent.type & 3) << 2) | ((m.parent.index & 7) << 4) | (m.parent.pointer ? 128 : 0)
      if (m.parent.pointer) {
        flags |=
          (m.parent.pointer.core ? 256 : 0) |
          ((m.parent.pointer.seq & 3) << 9) |
          (m.parent.pointer.offset ? 2048 : 0)
      }
    }

    c.uint.preencode(state, flags)

    if (m.info) c.uint.preencode(state, m.info)
    if (m.parent) encoding2_inline.preencode(state, m.parent)
  },
  encode(state, m) {
    let flags = (m.info ? 1 : 0) | (m.parent ? 2 : 0)
    if (m.parent) {
      flags |=
        ((m.parent.type & 3) << 2) | ((m.parent.index & 7) << 4) | (m.parent.pointer ? 128 : 0)
      if (m.parent.pointer) {
        flags |=
          (m.parent.pointer.core ? 256 : 0) |
          ((m.parent.pointer.seq & 3) << 9) |
          (m.parent.pointer.offset ? 2048 : 0)
      }
    }

    c.uint.encode(state, flags)

    if (m.info) c.uint.encode(state, m.info)
    if (m.parent) encoding2_inline.encode(state, m.parent)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      info: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      parent: (flags & 2) !== 0 ? encoding2_inline.decode(state, flags >>> 2) : null
    }
  }
}

// @namespace-1/pointer
const encoding1 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.core) c.uint.preencode(state, m.core)
    if (m.offset) c.uint.preencode(state, m.offset)
  },
  encode(state, m) {
    const flags = (m.core ? 1 : 0) | ((m.seq & 3) << 1) | (m.offset ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.core) c.uint.encode(state, m.core)
    if (m.offset) c.uint.encode(state, m.offset)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      core: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seq: (flags >>> 1) & 3,
      offset: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @namespace-1/pointer (inline)
const encoding1_inline = {
  preencode(state, m) {
    if (m.core) c.uint.preencode(state, m.core)
    if (m.offset) c.uint.preencode(state, m.offset)
  },
  encode(state, m) {
    if (m.core) c.uint.encode(state, m.core)
    if (m.offset) c.uint.encode(state, m.offset)
  },
  decode(state, inlining) {
    const flags = inlining

    return {
      core: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seq: (flags >>> 1) & 3,
      offset: (flags & 8) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @namespace-1/parent
const encoding2 = {
  preencode(state, m) {
    let flags = (m.type & 3) | ((m.index & 7) << 2) | (m.pointer ? 32 : 0)
    if (m.pointer) {
      flags |= (m.pointer.core ? 64 : 0) | ((m.pointer.seq & 3) << 7) | (m.pointer.offset ? 512 : 0)
    }

    c.uint.preencode(state, flags)

    if (m.pointer) encoding1_inline.preencode(state, m.pointer)
  },
  encode(state, m) {
    let flags = (m.type & 3) | ((m.index & 7) << 2) | (m.pointer ? 32 : 0)
    if (m.pointer) {
      flags |= (m.pointer.core ? 64 : 0) | ((m.pointer.seq & 3) << 7) | (m.pointer.offset ? 512 : 0)
    }

    c.uint.encode(state, flags)

    if (m.pointer) encoding1_inline.encode(state, m.pointer)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      type: flags & 3,
      index: (flags >>> 2) & 7,
      pointer: (flags & 32) !== 0 ? encoding1_inline.decode(state, flags >>> 6) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@namespace-1/parent2':
      return encoding0
    case '@namespace-1/pointer':
      return encoding1
    case '@namespace-1/parent':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
